name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 2 days
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -L -s -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://institute-app-kgur4uduugergbmaxkobvn.streamlit.app/ > /dev/null
          echo "App pinged successfully!"

